apiVersion: v1
kind: Namespace
metadata:
  name: my-nginx-e05mo6
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-e05mo6
  namespace: my-nginx-e05mo6
  labels:
    name: nginx-e05mo6
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx-e05mo6
  template:
    metadata:
      namespace: my-nginx-e05mo6
      labels:
        name: nginx-e05mo6
    spec:
      containers:
      - name: nginx-e05mo6
        image: nginx
        ports:
        - containerPort: 80

